name: Build LaTeX document
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            cleveref
            hyperref
            xetex
            babel-italian
            makecell
            etoolbox
            float
            caption
            fontspec
            beamer
          
      - name: Check `tlmgr` version
        run: tlmgr --version
      - name: Check `xelatex` version
        run: xelatex --version

      - name: Compile SwTesting
        run: cd SwTesting && xelatex main.tex && xelatex main.tex

      - name: Compile ProjMgmt
        run: cd ProjMgmt && xelatex main.tex && xelatex main.tex

      - name: Rename ProjMgmt file
        run: mv ProjMgmt/main.pdf ProjMgmt/pres_0350116.pdf
      - name: Rename SwTesting file
        run: mv SwTesting/main.pdf SwTesting/report_0350116.pdf
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: |
            ProjMgmt/pres_0350116.pdf
            SwTesting/report_0350116.pdf
