on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            cleveref
            hyperref
            xetex
            babel-italian
            beamer
          
      - name: Check `tlmgr` version
        run: tlmgr --version
      - name: Check `xelatex` version
        run: xelatex --version

      - name: Compile SwTesting
        run: cd SwTesting && xelatex main.tex

      - name: Compile ProjMgmt
        run: cd ProjMgmt && xelatex main.tex
