on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Choco install TeX Live
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install texlive -y
      - name: Build using XeTeX
        run: xetex --version
